# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_v42 env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]" env.actions.right_arm.controller.weight_ori="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_v43 env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]" env.actions.right_arm.controller.weight_ori="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_v44 env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]" env.actions.right_arm.controller.weight_ori="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_v45 env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]" env.actions.right_arm.controller.weight_ori="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2500 --run_name ik_v46 env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]" env.actions.right_arm.controller.weight_ori="[0., 0., 0., 0., 1.0, 1.0, 1.0]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2500 --run_name ik_v47
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v48 env.actions.right_arm.controller.ik_params="{"lambda_val": 0.05}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v49 env.actions.right_arm.controller.ik_params="{"lambda_val": 0.07}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v50 env.rewards.hand_pos_tracking.weight=-1.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v51 env.rewards.zmp_supp_dist.weight=0.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v52 env.rewards.hand_pos_tracking.weight=-0.5
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v53 env.rewards.hand_pos_tracking.weight=-0.2
# Cylindrical frame
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v54
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v55 env.rewards.hand_pos_tracking.weight=-0.5
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v56 env.rewards.zmp_supp_dist.weight=0. env.rewards.zmp_centroid_dist.weight=0.5
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v57 env.rewards.feet_slide.weight=0. 
# Eliminated foot slide reward
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v58
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v59 env.rewards.torso_acc_l2.weight=0. 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v60 env.rewards.approaching.weight=0.1
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v61 env.rewards.approaching.weight=0.3
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v62 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v63 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" env.rewards.approaching.weight=0.1
# Modified the approaching reward at the joint limit
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v64 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" env.rewards.approaching.weight=0.3
# Penalize torso acceleration
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v65 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v66 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" env.rewards.approaching.weight=0.1

# Penalize pelvis acc
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v67 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v68 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" env.rewards.approaching.weight=0.2
# Cartesian space sampling
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v69 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" 
# Sampled wrt to torso
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v70 env.commands.hands_pose.ranges.z_range="[0.3, 1.1]" 
# Sampled wrt to root, updated sigma, changed z range
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v71 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v72 env.rewards.approaching.weight=0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v73 env.rewards.approaching.weight=0.5
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v74 env.rewards.pelvis_acc_l2.weight=0. 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v75 env.rewards.pelvis_acc_l2.weight=0. env.rewards.approaching.weight=0.5
# After the bug fix in the command sampling
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v76 env.rewards.pelvis_acc_l2.weight=0. 
# Modified joint velocity coef
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2500 --run_name ik_v77 env.rewards.pelvis_acc_l2.weight=0. 
# Modified initial target pose
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2500 --run_name ik_v78 env.rewards.pelvis_acc_l2.weight=0. 
# Sample wrt the avg foot frame and changed xrange
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2500 --run_name ik_v79 env.rewards.pelvis_acc_l2.weight=0. 
# Added hand pose to the observations
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v81 env.rewards.pelvis_acc_l2.weight=0. 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v82 env.rewards.pelvis_acc_l2.weight=0. env.rewards.approaching.weight=0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v83 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v84 env.rewards.pelvis_acc_l2.weight=0. env.rewards.approaching.weight=0.5
# Modified the target pose generator(stationary at the end), and adopted maintaining target reward
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v85 env.rewards.pelvis_acc_l2.weight=0. 

# Obs without command and hands pose
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v86 env.rewards.pelvis_acc_l2.weight=0. 
# Obs with the delta lin, angmom, changed the xrange
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v87 env.rewards.pelvis_acc_l2.weight=0. 
# Modified rewards that they only handle the controllable joints
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_v88 env.rewards.pelvis_acc_l2.weight=0. 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v89 env.rewards.pelvis_acc_l2.weight=0. env.observations.policy.momentum_change.scale=0. env.observations.policy.momentum.scale=0.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v90 env.rewards.pelvis_acc_l2.weight=0. env.observations.policy.momentum.scale=0.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v91 env.rewards.pelvis_acc_l2.weight=0. env.observations.policy.momentum_change.scale=0. 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v92 env.rewards.pelvis_acc_l2.weight=0. env.observations.policy.momentum_change.scale=0. env.observations.policy.momentum.scale=0. env.rewards.approaching.weight=0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v93 env.rewards.pelvis_acc_l2.weight=0.  env.observations.policy.momentum.scale=0. env.rewards.approaching.weight=0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v94 env.rewards.pelvis_acc_l2.weight=0. env.observations.policy.momentum_change.scale=0.  env.rewards.approaching.weight=0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_v89 env.rewards.pelvis_acc_l2.weight=0. env.observations.policy.momentum_change.scale=0. env.observations.policy.momentum.scale=0. env.rewards.maintain_target.weight=10.

# Now we implemented various dof IK contoller(rest is controlled by rl)
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_7dof_v1 env.rewards.approaching.weight=0.1
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v1 env.rewards.approaching.weight=0.1
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK5-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_5dof_v1 env.rewards.approaching.weight=0.1
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK0-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_0dof_v1 env.rewards.approaching.weight=0.1


# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_7dof_v2 env.rewards.approaching.weight=0.3
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v2 env.rewards.approaching.weight=0.3
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK5-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_5dof_v2 env.rewards.approaching.weight=0.3
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK0-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_0dof_v2 env.rewards.approaching.weight=0.3

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_7dof_v3 env.rewards.approaching.weight=0.2 env.actions.right_arm.controller.ik_params="{"lambda_val": 0.2}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v3 env.rewards.approaching.weight=0.2 env.actions.right_arm.controller.ik_params="{"lambda_val": 0.2}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_7dof_v4 env.rewards.approaching.weight=0.2 env.actions.right_arm.controller.ik_params="{"lambda_val": 0.05}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v4 env.rewards.approaching.weight=0.2 env.actions.right_arm.controller.ik_params="{"lambda_val": 0.05}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_7dof_v5 env.rewards.approaching.weight=0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v5 env.rewards.approaching.weight=0.2

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v5 env.rewards.approaching.weight=0.3 env.actions.right_arm.controller.use_weighted_jacobian=True env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 0., 0., 0.]" env.actions.right_arm.controller.weight_ori="[0., 0., 0., 1.0, 1.0, 1.0]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_7dof_v5 env.rewards.approaching.weight=0.3 env.actions.right_arm.controller.use_weighted_jacobian=True env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 1.0, 0., 0., 0.]" env.actions.right_arm.controller.weight_ori="[0., 0., 0., 0., 1.0, 1.0, 1.0]"

# In foot frame
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v6 env.rewards.approaching.weight=0.3 env.actions.right_arm.controller.use_weighted_jacobian=True env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 0., 0., 0.]" env.actions.right_arm.controller.weight_ori="[0., 0., 0., 1.0, 1.0, 1.0]"
# New rel torque reward, modified sigma of approaching reward
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v7 env.rewards.approaching.weight=0.3 env.actions.right_arm.controller.use_weighted_jacobian=True env.actions.right_arm.controller.weight_pos="[1.0, 1.0, 1.0, 0., 0., 0.]" env.actions.right_arm.controller.weight_ori="[0., 0., 0., 1.0, 1.0, 1.0]"

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_6dof_v8 env.rewards.approaching.weight=0.2 env.rewards.approaching.params="{"penalize_joint_limit": False}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_6dof_v7 env.rewards.approaching.weight=0.2 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_6dof_v9 env.rewards.approaching.weight=0.2 env.actions.right_arm.controller.use_weighted_jacobian=False
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_7dof_v7 env.rewards.approaching.weight=0.2 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_7dof_v8 env.rewards.approaching.weight=0.2 env.rewards.approaching.params="{"penalize_joint_limit": False}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 2000 --run_name ik_7dof_v9 env.rewards.approaching.weight=0.2 env.actions.right_arm.controller.use_weighted_jacobian=False

# Comming back to the RL domain
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name relq_v0  
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name relq_v1
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name relq_v2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name relq_v3

# IK domain with proper observations, and adopted clipping for IK solution
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK5-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_5dof_v12 env.rewards.approaching.weight=0.3
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK7-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_7dof_v12 env.rewards.approaching.weight=0.3
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3500 --run_name ik_6dof_v12 env.rewards.approaching.weight=0.3

# 6dof IK controller with angle noise, and the foot slide penalty
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v13 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.commands.hands_pose.angle_noise=15.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v14 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.commands.hands_pose.angle_noise=30.

# Both arm testing
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-Both-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_both_v0
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-Both-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_both_v1 env.rewards.approaching_right.weight=0. env.rewards.approaching_left.weight=0.

# Reduced sigma for arm tracking
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-Both-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_both_v2

# Again, test 6dof IK controller 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v16 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.commands.hands_pose.angle_noise=15. env.actions.right_arm.controller.use_max_clipping=True env.actions.right_arm.controller.max_delta_pos=0.5
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v17 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.commands.hands_pose.angle_noise=15. env.actions.right_arm.controller.use_max_clipping=False
# # Added jumping termination
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-Both-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_both_v3

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v18 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.commands.hands_pose.angle_noise=15. env.actions.right_arm.controller.use_max_clipping=True env.actions.right_arm.controller.max_delta_pos=1.0

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v0 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.5
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v1 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-5.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v2 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-5. env.actions.right_arm_res.scale=0.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v3 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-5.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v4 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-1.
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v5 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-10.

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK6-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_6dof_v16 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.commands.hands_pose.angle_noise=15. env.actions.right_arm.controller.use_max_clipping=True env.actions.right_arm.controller.max_delta_pos=0.5
# IK residual updates
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v6 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v7 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.05
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v8 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=0.

# Command bug fixes
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v9 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2
# Changed arm action scale and the reward scale
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v10 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.05
# Adopted clipping to the residual actions
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v11 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v12 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.05
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v13 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v14 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v15 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.4
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v16 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.05
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v17 env.rewards.approaching.weight=0.1 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2

# Added arm joints to the reward computation
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v18 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2

# added curr hand pose in the robot body frame, adopted action rate penalty for residual action
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v19 env.rewards.approaching.weight=0.3 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v20 env.rewards.approaching.weight=0.1 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2

# Fine-tuning rewards
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v21 env.rewards.approaching.weight=0.2 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.2
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v22 env.rewards.approaching.weight=0.2 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.1
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v23 env.rewards.approaching.weight=0.2 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.4
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v24 env.rewards.approaching.weight=0.2 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.6
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 6000 --run_name ik_res_v25 env.rewards.approaching.weight=0.1 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.4
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 6000 --run_name ik_res_v26 env.rewards.approaching.weight=0.1 env.rewards.feet_slide.weight=-0.5 env.rewards.residual_action_norm.weight=-0.05
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v27 env.rewards.residual_action_norm.weight=-0.4 env.rewards.approaching.weight=0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v28 env.rewards.residual_action_norm.weight=-0.1 env.rewards.approaching.weight=0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v29 env.rewards.residual_action_norm.weight=-0.1 env.rewards.approaching.weight=0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]" env.rewards.approaching.params="{"sigma": 10.}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v30 env.rewards.residual_action_norm.weight=-0.4 env.rewards.approaching.weight=0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]" env.rewards.approaching.params="{"sigma": 10.}"
# Eliminated the arm for torque and velocity penalty

# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v32 env.rewards.residual_action_norm.weight=-0.1 env.rewards.approaching.weight=0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]" env.rewards.approaching.params="{"sigma": 10.}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v33 env.rewards.residual_action_norm.weight=-0.4 env.rewards.approaching.weight=0.2 env.actions.right_arm_res.clip_range="[-0.5, 0.5]" env.rewards.approaching.params="{"sigma": 10.}"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v34 env.rewards.residual_action_norm.weight=-0.1 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v35 env.rewards.residual_action_norm.weight=0. env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v36 env.rewards.residual_action_norm.weight=0. env.rewards.approaching.weight=0.3 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v37 env.rewards.residual_action_norm.weight=-0.05 env.rewards.approaching.weight=0.3 
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v38 env.rewards.residual_action_norm.weight=-0.1 env.rewards.approaching.weight=0.3 env.rewards.residual_action_rate_l2.weight=-0.0005
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v39 env.rewards.residual_action_norm.weight=-0.1 env.rewards.approaching.weight=0.3 env.rewards.residual_action_rate_l2.weight=-0.01
# Modified action norm reward into raw actions
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v40 env.rewards.residual_action_norm.weight=-0.05 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v41 env.rewards.residual_action_norm.weight=-0.01 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.5, 0.5]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v41 env.rewards.residual_action_norm.weight=-0.01 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.1, 0.1]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v42 env.rewards.residual_action_norm.weight=-0.05 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.2, 0.2]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v43 env.rewards.residual_action_norm.weight=0. env.rewards.residual_action_limit.weight=-0.2 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.2, 0.2]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 4000 --run_name ik_res_v44 env.rewards.residual_action_norm.weight=-0.05 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.1, 0.1]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v45 env.rewards.residual_action_norm.weight=0. env.rewards.residual_action_limit.weight=-0.4 env.rewards.approaching.weight=0.3 env.actions.right_arm_res.clip_range="[-0.2, 0.2]"

# v43 is finally working
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v46 env.rewards.residual_action_limit.weight=-0.1 env.rewards.energy.weight=0. env.actions.right_arm_res.clip_range="[-0.2, 0.2]"
# python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 5000 --run_name ik_res_v47 env.rewards.residual_action_limit.weight=-0.1 env.actions.right_arm_res.clip_range="[-0.2, 0.2]"

# Runs with right arm energy, vel, acc penalty
python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v48 env.rewards.residual_action_limit.weight=-0.1 env.actions.right_arm_res.clip_range="[-0.2, 0.2]"
python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_v49 env.rewards.residual_action_limit.weight=-0.2 env.actions.right_arm_res.clip_range="[-0.2, 0.2]"

# TODOS: Compare if penalizing right arm energy, vel, acc does affects the performance
python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-both-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_both_v0 env.rewards.residual_action_limit_left.weight=-0.1 env.rewards.residual_action_limit_right.weight=-0.1 env.rewards.approaching_right.weight=0.2 env.rewards.approaching_left.weight=0.2
python3 source/standalone/workflows/rsl_rl/train.py --task Arm-track-both-IK-res-G1-v0 --num_envs 4096 --headless --logger wandb --log_project_name humanoid --max_iterations 3000 --run_name ik_res_both_v1 env.rewards.residual_action_limit_left.weight=-0.1 env.rewards.residual_action_limit_right.weight=-0.1 env.rewards.approaching_right.weight=0. env.rewards.approaching_left.weight=0.